language: node_js
node_js:
        - "node"

cache: yarn

services: 
        - docker

script:
  - docker build -t frontend-hilbert .

deploy:
        provider: s3
        region: ap-southeast-1
        bucket: frontend-hilbert
        skip_cleanup: true
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY 
